export default {
  PopupContentAboutUs: () => import('./PopupContentAboutUs'),
  PopupContentHistory: () => import('./PopupContentHistory'),
  PopupContentOurGoal: () => import('./PopupContentOurGoal'),
  PopupContentFacts: () => import('./PopupContentFacts'),
  PopupContentFlatMove: () => import('./PopupContentFlatMove'),
  PopupContentOfficeMove: () => import('./PopupContentOfficeMove'),
  PopupContentStuffMove: () => import('./PopupContentStuffMove'),
  PopupContentSpecialists: () => import('./PopupContentSpecialists'),
  PopupContentPayment: () => import('./PopupContentPayment'),
  PopupContentSpecialOffers: () => import('./PopupContentSpecialOffers'),
  PopupContentAuto: () => import('./PopupContentAuto'),
  PopupContentPackage: () => import('./PopupContentPackage'),
  PopupContentContacts: () => import('./PopupContentContacts'),
  PopupContentJobs: () => import('./PopupContentJobs'),
  PopupContentFeedback: () => import('./PopupContentFeedback'),
  PopupContentPartners: () => import('./PopupContentPartners'),
};
